metrics_processor_name: "PandaPowerMetricsProcessor"

dataset_versions:

  - name: "Standard"
    path: "/Users/balthazardonon/Documents/postdoc/data/PSCC24/vanilla_no_filter/test"
    color: "#3180b5"

  - name: "Condenser"
    path: "/Users/balthazardonon/Documents/postdoc/data/PSCC24/condenser_no_filter/test"
    color: "#37a048"

  - name: "Reduced"
    path: "/Users/balthazardonon/Documents/postdoc/data/PSCC24/reduced_no_filter/test"
    color: "#da0561"

#  - name: "Start"
#    path: "/Users/balthazardonon/Documents/postdoc/data/PSCC24/vanilla_no_filter/test"
#    color: "tab:blue"
#
#  - name: "OPF"
#    path: "/Users/balthazardonon/Documents/postdoc/data/PSCC24/vanilla_no_filter/test_cet/soft_constraints_pandapower"
#    color: "#4997e1"
#
#  - name: "GNN"
#    path: "/Users/balthazardonon/Documents/postdoc/data/PSCC24/vanilla_no_filter/test_trained_on_vanilla_version=12_336"
#    color: "#91c0ed"

modes:
  focus_modes:
    all: True
    object: False
    snapshot: False
  display_modes:
    plot: True
    table: False
  statistics_modes:
    summary: True
    correlation: False

figure_settings:
  night_mode: false
  figsize: [5, 2]
  grid: [1, 3]
  extension: '.pgf'
  title: False
